# Generated by Django 5.2.7 on 2025-10-25 21:29

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from=models.CharField(max_length=100), unique=True),
        ),
    ]
